import { BanknoteArrowDown, CircleDollarSign, ShieldCheck, ShieldX } from "lucide-react";
import { obtenerFianzas } from "@/lib/fianzas";
import { obtenerHabitaciones } from "@/lib/habitaciones";
import { obtenerInquilinos } from "@/lib/inquilinos";
import { obtenerViviendas } from "@/lib/viviendas";
import { ReactNode } from "react";

export const dynamic = "force-dynamic";

const moneda = new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" });
const fecha = (valor: string | null) => valor ? new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${valor.slice(0, 10)}T00:00:00`)) : "-";
function Tarjeta({ titulo, importe, detalle, icono, color }: { titulo: string; importe: number; detalle: string; icono: ReactNode; color: string }) { return <article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className={`flex items-center gap-3 ${color}`}>{icono}<span className="text-sm font-medium text-slate-600">{titulo}</span></div><p className="mt-4 text-3xl font-bold text-slate-900">{moneda.format(importe)}</p><p className="mt-1 text-sm text-slate-500">{detalle}</p></article>; }

export default async function FianzasPage() {
  const [fianzas, inquilinos, habitaciones, viviendas] = await Promise.all([obtenerFianzas(), obtenerInquilinos(), obtenerHabitaciones(), obtenerViviendas()]);
  const filtrar = (estado: string) => fianzas.filter((fianza) => fianza.estado === estado);
  const enDeposito = filtrar("COBRADA");
  const porRevisar = filtrar("PENDIENTE_REVISION");
  const devueltas = filtrar("DEVUELTA");
  const retenidas = filtrar("RETENIDA");
  const total = (items: typeof fianzas, campo: "importe" | "importe_devuelto" | "importe_retenido" = "importe") => items.reduce((suma, item) => suma + Number(item[campo]), 0);
  const totalEntregado = (items: typeof fianzas) => items.reduce((suma, item) => suma + Number(item.importe_entregado), 0);
  const estado = (valor: string) => valor === "COBRADA" ? ["En deposito", "bg-blue-50 text-blue-700"] : valor === "DEVUELTA" ? ["Devuelta", "bg-green-50 text-green-700"] : valor === "RETENIDA" ? ["Retenida", "bg-amber-50 text-amber-700"] : ["Revisar", "bg-violet-50 text-violet-700"];

  return <div>
    <div className="flex items-start justify-between gap-6"><div><h1 className="text-3xl font-bold text-slate-900">Fianzas</h1><p className="mt-2 text-slate-500">Control de depositos, devoluciones y retenciones. Las fianzas no se contabilizan como ingresos de alquiler.</p></div><div className="rounded-xl bg-blue-50 px-4 py-3 text-right text-blue-700"><div className="text-2xl font-bold">{fianzas.length}</div><div className="text-sm font-medium">fianzas registradas</div></div></div>
    <section className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Tarjeta titulo="En depósito" importe={totalEntregado(enDeposito)} detalle={`${enDeposito.length} fianza${enDeposito.length === 1 ? "" : "s"} con importe entregado`} icono={<ShieldCheck size={22} />} color="text-blue-600" /><Tarjeta titulo="Históricas por revisar" importe={totalEntregado(porRevisar)} detalle={`${porRevisar.length} estancia${porRevisar.length === 1 ? "" : "s"} finalizada${porRevisar.length === 1 ? "" : "s"}`} icono={<CircleDollarSign size={22} />} color="text-violet-600" /><Tarjeta titulo="Devuelto" importe={total(devueltas, "importe_devuelto")} detalle={`${devueltas.length} devolución${devueltas.length === 1 ? "" : "es"} realizada${devueltas.length === 1 ? "" : "s"}`} icono={<BanknoteArrowDown size={22} />} color="text-green-600" /><Tarjeta titulo="Retenido para gastos" importe={total(retenidas, "importe_retenido")} detalle={`${retenidas.length} retención${retenidas.length === 1 ? "" : "es"}; no es renta`} icono={<ShieldX size={22} />} color="text-amber-600" /></section>
    <section className="mt-8 overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div className="flex items-center gap-3 border-b border-slate-200 p-5"><div className="rounded-lg bg-blue-100 p-2 text-blue-600"><CircleDollarSign size={21} /></div><div><h2 className="font-bold text-slate-900">Registro de fianzas</h2><p className="text-sm text-slate-500">Las fianzas historicas finalizadas se marcan para revisar, sin inventar una devolucion ni un ingreso.</p></div></div>{fianzas.length === 0 ? <p className="p-10 text-center text-slate-500">No hay fianzas registradas.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-slate-50 text-sm text-slate-600"><tr><th className="px-5 py-4 font-semibold">Inquilino</th><th className="px-5 py-4 font-semibold">Vivienda / habitacion</th><th className="px-5 py-4 font-semibold">Cobro</th><th className="px-5 py-4 font-semibold">Importe</th><th className="px-5 py-4 font-semibold">Resolucion</th><th className="px-5 py-4 font-semibold">Estado</th></tr></thead><tbody>{fianzas.map((fianza) => { const inquilino = inquilinos.find((item) => item.id === fianza.inquilino_id); const habitacion = habitaciones.find((item) => item.id === fianza.habitacion_id); const vivienda = habitacion && viviendas.find((item) => item.id === habitacion.vivienda_id); const [nombreEstado, estiloEstado] = estado(fianza.estado); return <tr key={fianza.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-5 py-4"><p className="font-semibold text-slate-900">{inquilino ? `${inquilino.nombre} ${inquilino.apellidos}` : "Inquilino eliminado"}</p><p className="mt-1 text-sm text-slate-500">{inquilino?.documento || "Sin documento"}</p></td><td className="px-5 py-4 text-slate-700">{vivienda?.nombre ?? "-"} / {habitacion?.codigo ?? "-"}</td><td className="px-5 py-4 text-slate-600">{fecha(fianza.fecha_cobro)}</td><td className="px-5 py-4 font-semibold text-slate-900">{moneda.format(Number(fianza.importe))}</td><td className="px-5 py-4 text-slate-600">{fianza.estado === "COBRADA" ? "Pendiente" : fianza.estado === "PENDIENTE_REVISION" ? "Revisar historial" : <><p>{fecha(fianza.fecha_resolucion)}</p>{fianza.motivo_retencion && <p className="mt-1 max-w-xs text-xs text-slate-500">{fianza.motivo_retencion}</p>}</>}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${estiloEstado}`}>{nombreEstado}</span></td></tr>; })}</tbody></table></div>}</section>
  </div>;
}
