"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Download, FileText, Pencil, Save, Trash2, Upload, UserRound } from "lucide-react";
import { DocumentoInquilino, Estancia, Habitacion, Inquilino, Vivienda } from "@/types";
import { actualizarInquilino, eliminarInquilino } from "@/lib/inquilinos";
import { abrirDocumentoInquilino, eliminarDocumentoInquilino, eliminarDocumentosInquilino, subirDocumentoInquilino } from "@/lib/documentosInquilino";

type Props = { inquilino: Inquilino; estancias: Estancia[]; habitaciones: Habitacion[]; viviendas: Vivienda[]; documentosIniciales: DocumentoInquilino[] };
const campos = [["nombre", "Nombre"], ["apellidos", "Apellidos"], ["documento", "DNI / NIE / Pasaporte"], ["telefono", "Telefono"], ["email", "Email"], ["fecha_nacimiento", "Fecha de nacimiento"], ["nacionalidad", "Nacionalidad"], ["profesion", "Profesion"], ["empresa", "Empresa"]] as const;
function fechaLocal(fecha: string | null) { return fecha ? new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${fecha.slice(0, 10)}T00:00:00`)) : "En curso"; }
function tamanoLegible(tamano: number | null) { return !tamano ? "Archivo" : tamano < 1_000_000 ? `${Math.ceil(tamano / 1024)} KB` : `${(tamano / 1_000_000).toFixed(1)} MB`; }

export default function InquilinoPerfil({ inquilino, estancias, habitaciones, viviendas, documentosIniciales }: Props) {
  const router = useRouter();
  const [editando, setEditando] = useState(false); const [guardando, setGuardando] = useState(false); const [subiendo, setSubiendo] = useState(false); const [borrando, setBorrando] = useState(false); const [documentos, setDocumentos] = useState(documentosIniciales);
  const [datos, setDatos] = useState({ nombre: inquilino.nombre, apellidos: inquilino.apellidos ?? "", documento: inquilino.documento ?? "", telefono: inquilino.telefono ?? "", email: inquilino.email ?? "", fecha_nacimiento: inquilino.fecha_nacimiento ?? "", nacionalidad: inquilino.nacionalidad ?? "", profesion: inquilino.profesion ?? "", empresa: inquilino.empresa ?? "", observaciones: inquilino.observaciones ?? "" });
  async function guardar(evento: FormEvent) { evento.preventDefault(); if (!datos.nombre.trim()) return alert("El nombre es obligatorio."); setGuardando(true); try { await actualizarInquilino(inquilino.id, Object.fromEntries(Object.entries(datos).map(([clave, valor]) => [clave, valor.trim() || null]))); setEditando(false); router.refresh(); } catch (error) { alert(error instanceof Error ? error.message : "No se pudieron guardar los cambios."); } finally { setGuardando(false); } }
  async function adjuntar(evento: ChangeEvent<HTMLInputElement>) { const archivo = evento.target.files?.[0]; evento.target.value = ""; if (!archivo) return; setSubiendo(true); try { const documento = await subirDocumentoInquilino(inquilino.id, archivo); setDocumentos((actuales) => [documento, ...actuales]); } catch (error) { alert(error instanceof Error ? error.message : "No se pudo subir el documento."); } finally { setSubiendo(false); } }
  async function abrir(documento: DocumentoInquilino) { try { window.open(await abrirDocumentoInquilino(documento), "_blank", "noopener,noreferrer"); } catch (error) { alert(error instanceof Error ? error.message : "No se pudo abrir el documento."); } }
  async function eliminarDocumento(documento: DocumentoInquilino) { if (!confirm(`Eliminar ${documento.nombre}?`)) return; try { await eliminarDocumentoInquilino(documento); setDocumentos((actuales) => actuales.filter((item) => item.id !== documento.id)); } catch (error) { alert(error instanceof Error ? error.message : "No se pudo eliminar el documento."); } }
  async function borrarInquilino() { if (!confirm(`Vas a borrar definitivamente a ${inquilino.nombre} ${inquilino.apellidos}. Tambien se eliminaran su historial y documentos. Continuar?`)) return; setBorrando(true); try { await eliminarDocumentosInquilino(inquilino.id); await eliminarInquilino(inquilino.id); router.push("/inquilinos"); router.refresh(); } catch (error) { alert(error instanceof Error ? error.message : "No se pudo borrar el inquilino."); setBorrando(false); } }
  return <div className="mx-auto max-w-6xl"><Link href="/inquilinos" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600 hover:text-blue-800"><ArrowLeft size={17} /> Volver a inquilinos</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4"><div className="rounded-2xl bg-blue-100 p-4 text-blue-700"><UserRound size={30} /></div><div><h1 className="text-3xl font-bold text-slate-900">{inquilino.nombre} {inquilino.apellidos}</h1><p className="mt-1 text-slate-500">{inquilino.activo ? "Inquilino activo" : "Estancia finalizada"} · Desde {fechaLocal(inquilino.fecha_entrada)}</p></div></div><div className="flex gap-3"><button onClick={() => setEditando(true)} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 font-semibold text-white hover:bg-blue-700"><Pencil size={17} /> Editar datos</button><button onClick={borrarInquilino} disabled={borrando} className="inline-flex items-center gap-2 rounded-lg border border-red-200 px-4 py-2.5 font-semibold text-red-700 hover:bg-red-50 disabled:opacity-60"><Trash2 size={17} /> {borrando ? "Borrando..." : "Borrar"}</button></div></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-3"><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 lg:col-span-2"><h2 className="text-lg font-bold text-slate-900">Trayectoria en RoomFlow</h2><p className="mt-1 text-sm text-slate-500">Habitaciones ocupadas, con sus fechas y condiciones.</p><div className="mt-5 space-y-4">{estancias.length ? estancias.map((estancia) => { const habitacion = habitaciones.find((item) => item.id === estancia.habitacion_id); const vivienda = habitacion && viviendas.find((item) => item.id === habitacion.vivienda_id); return <div key={estancia.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div><p className="font-semibold text-slate-900">{vivienda?.nombre ?? "Vivienda eliminada"} · Habitacion {habitacion?.codigo ?? "—"}</p><p className="mt-1 text-sm text-slate-500">Desde {fechaLocal(estancia.fecha_entrada)} hasta {fechaLocal(estancia.fecha_salida)}</p></div><div className="text-right"><span className={`rounded-full px-3 py-1 text-xs font-bold ${estancia.estado === "ACTIVA" ? "bg-green-50 text-green-700" : "bg-slate-100 text-slate-600"}`}>{estancia.estado === "ACTIVA" ? "En curso" : "Finalizada"}</span><p className="mt-2 text-sm font-medium text-slate-700">{Number(estancia.precio + estancia.gastos).toFixed(2)} EUR / mes</p></div></div>; }) : <p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Aun no hay historial registrado. Las nuevas entradas y salidas se guardaran aqui automaticamente.</p>}</div></section><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-lg font-bold text-slate-900">Contacto</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-slate-500">Telefono</dt><dd className="font-medium text-slate-800">{inquilino.telefono || "Sin registrar"}</dd></div><div><dt className="text-slate-500">Email</dt><dd className="break-all font-medium text-slate-800">{inquilino.email || "Sin registrar"}</dd></div><div><dt className="text-slate-500">Documento</dt><dd className="font-medium text-slate-800">{inquilino.documento || "Sin registrar"}</dd></div></dl></section></div>
    <section className="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">Documentos</h2><p className="mt-1 text-sm text-slate-500">Contratos, identificaciones y archivos aportados por el inquilino.</p></div><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800"><Upload size={17} /> {subiendo ? "Subiendo..." : "Anadir documento"}<input type="file" className="hidden" onChange={adjuntar} disabled={subiendo} /></label></div><div className="mt-5 divide-y divide-slate-100">{documentos.length ? documentos.map((documento) => <div key={documento.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="flex items-center gap-3"><FileText className="text-blue-600" size={22} /><div><p className="font-medium text-slate-800">{documento.nombre}</p><p className="text-xs text-slate-500">{tamanoLegible(documento.tamano)} · Anadido {fechaLocal(documento.created_at)}</p></div></div><div className="flex gap-2"><button onClick={() => abrir(documento)} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100" title="Abrir o descargar"><Download size={18} /></button><button onClick={() => eliminarDocumento(documento)} className="rounded-lg p-2 text-red-600 hover:bg-red-50" title="Eliminar documento"><Trash2 size={18} /></button></div></div>) : <p className="py-5 text-sm text-slate-500">No hay documentos adjuntos.</p>}</div></section>
    {editando && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><form onSubmit={guardar} className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold text-slate-900">Editar datos del inquilino</h2><p className="text-sm text-slate-500">Actualiza la informacion de contacto y personal.</p></div><button type="button" onClick={() => setEditando(false)} className="text-slate-500 hover:text-slate-800">Cancelar</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{campos.map(([clave, etiqueta]) => <label key={clave} className="text-sm font-medium text-slate-700">{etiqueta}<input type={clave === "email" ? "email" : clave === "fecha_nacimiento" ? "date" : "text"} value={datos[clave]} onChange={(evento) => setDatos({ ...datos, [clave]: evento.target.value })} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2 text-slate-900 outline-none focus:border-blue-500" /></label>)}</div><label className="mt-4 block text-sm font-medium text-slate-700">Observaciones<textarea value={datos.observaciones} onChange={(evento) => setDatos({ ...datos, observaciones: evento.target.value })} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2 text-slate-900 outline-none focus:border-blue-500" rows={4} /></label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setEditando(false)} className="rounded-lg border px-4 py-2 font-semibold text-slate-700">Cancelar</button><button disabled={guardando} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-60"><Save size={17} /> {guardando ? "Guardando..." : "Guardar cambios"}</button></div></form></div>}
  </div>;
}
